sizes: { 'train': 60, 'test': 60, 'np_test': 600 }
dataset_type: 'graffiti'
views: [6]
points: [80]
knn: 5
descriptor_dim: 132 # 128 (sift) + 2 (x-y) + 1 (scale) + 1 (orien)
rndseed: 6815
dtype: 'float32'

