sizes: { 'train': 40000, 'test': 3000, 'np_test': 500 }
dataset_type: 'synth'
views: [6]
points: [25]
points_scale: 1
descriptor_dim: 12
descriptor_var: 1.0
descriptor_noise_var: 0.05
dtype: 'float32'

