sizes: { 'train': 40000, 'test': 3000, 'np_test': 500 }
dataset_type: 'synthnoise'
views: [9]
points: [25]
descriptor_dim: 12
descriptor_var: 1.0
descriptor_noise_var: 0.05
noise_level: 0.1
subnoise_level: 0.05
num_repeats: 5
dtype: 'float32'

